### ISSUE TITLE
動的に確保したローカル配列をgmoveの左辺に使用できない

### ISSUE THREAD

**Issue by ytn86** [omni-compiler/omni-compiler#141]
以下のように, 動的に確保したローカル配列 `loArray` に対しgmoveを使用することができません.

* 環境
```
$ xmpcc --version
Version:1.1.0
``` 

* コード
```
#include <stdio.h>
#include <stdlib.h>
#include <xmp.h>

#pragma xmp nodes p(4)
#pragma xmp template t(0:9)
#pragma xmp distribute t(block) onto p


int main()
{
	double *array;
#pragma xmp align array[i] with t(i)
	double *loArray;

	array = (double *)xmp_malloc(xmp_desc_of(array), sizeof(double)*10);
	loArray = (double *)malloc(sizeof(double)*10);
	
#pragma xmp gmove
	loArray[0:9] = array[0:9];

	return 0;
}
	
```

* エラー
```
fatal: [XcalableMP] buildGmoveDesc: SUB_ARRAY_REF for non-arrayfatal: [XcalableMP] buildGmoveDesc: SUB_ARRAY_REF for non-array

java.lang.Exception: Stack tracejava.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1365)	at java.lang.Thread.dumpStack(Thread.java:1365)
	at xcodeml.util.XmLog.fatal(XmLog.java:89)	at xcodeml.util.XmLog.fatal(XmLog.java:89)
	at exc.xcalablemp.XMP.fatal(XMP.java:54)	at exc.xcalablemp.XMP.fatal(XMP.java:54)
	at exc.xcalablemp.XMPtranslateLocalPragma.buildGmoveDesc(XMPtranslateLocalPragma.java:2956)	at exc.xcalablemp.XMPtranslateLocalPragma.buildGmoveDesc(XMPtranslateLocalPragma.java:2956)
	at exc.xcalablemp.XMPtranslateLocalPragma.translateGmove(XMPtranslateLocalPragma.java:2851)	at exc.xcalablemp.XMPtranslateLocalPragma.translateGmove(XMPtranslateLocalPragma.java:2851)
	at exc.xcalablemp.XMPtranslateLocalPragma.translatePragma(XMPtranslateLocalPragma.java:99)	at exc.xcalablemp.XMPtranslateLocalPragma.translatePragma(XMPtranslateLocalPragma.java:99)
	at exc.xcalablemp.XMPtranslateLocalPragma.translate(XMPtranslateLocalPragma.java:47)
	at exc.xcalablemp.XMPtranslate.translate(XMPtranslate.java:65)
	at exc.xcalablemp.XMPtranslate.doDef(XMPtranslate.java:36)
	at exc.xcalablemp.XMPtranslateLocalPragma.translate(XMPtranslateLocalPragma.java:47)
	at exc.xcalablemp.XMPtranslate.translate(XMPtranslate.java:65)
	at exc.xcalablemp.XMPtranslate.doDef(XMPtranslate.java:36)
	at exc.object.XobjectDefEnv.iterateDef(XobjectDefEnv.java:91)	at exc.object.XobjectDefEnv.iterateDef(XobjectDefEnv.java:91)
	at exc.util.omompx.main(omompx.java:348)	at exc.util.omompx.main(omompx.java:348)
```

**Comment by h-murai** [comment]
fixしました。

以下は注意点です。

- １次元配列としてのポインタのみ扱えます。
- xmp_malloc の第2引数以降は、バイト数ではなく要素数です。

```C
array = (double *)xmp_malloc(xmp_desc_of(array), 10);
```

- XMP/C における3つ組の2番目は、上限ではなく要素数です。

```C
	loArray[0:10] = array[0:10];
```

**Comment by ytn86** [comment]
修正いただきありがとうございます.
またご指摘いただきありがとうございます.
