### ISSUE TITLE
allocated 引数のメンバ配列を coarray check し Abort

### ISSUE THREAD

**Issue by a-wada-rk** [omni-compiler/omni-compiler#20]
環境は任意。

[TP]

    MODULE real_poly_module
      TYPE,PUBLIC :: real_poly
        REAL,ALLOCATABLE :: coeff(:)
      END TYPE
    END MODULE

    PROGRAM example
      USE real_poly_module
      TYPE(real_poly) poly1
      poly1 = real_poly((/1.0,2.0,4.0/))
      IF (.NOT.ALLOCATED(poly1%coeff)) STOP 'NOT ALLOCATED'
    END

[現象]

    >> xmpf90 020.f90
    Exception in thread "main" java.lang.UnsupportedOperationException: (MEMBER_REF:A1683fb0 (F_VAR_REF:S16846e0 (VAR:S16846e0 poly1)) (IDENT coeff))
    	at exc.object.XobjList.getName(XobjList.java:389)
    	at exc.xmpF.XMPtransCoarrayRun._findCoarrayInCoarrays(XMPtransCoarrayRun.java:2218)
    	at exc.xmpF.XMPtransCoarrayRun._isCoarrayInCoarrays(XMPtransCoarrayRun.java:2211)
    	at exc.xmpF.XMPtransCoarrayRun._replaceAllocatedWithAssociated(XMPtransCoarrayRun.java:2834)
    	at exc.xmpF.XMPtransCoarrayRun.replaceIntrinsicCalls2(XMPtransCoarrayRun.java:2609)
    	at exc.xmpF.XMPtransCoarrayRun.transExecPart(XMPtransCoarrayRun.java:1191)
    	at exc.xmpF.XMPtransCoarrayRun.run1_procedure(XMPtransCoarrayRun.java:546)
    	at exc.xmpF.XMPtransCoarrayRun.run1(XMPtransCoarrayRun.java:518)
    	at exc.xmpF.XMPtransCoarray.doDef(XMPtransCoarray.java:103)
    	at exc.object.XobjectDefEnv.iterateDef(XobjectDefEnv.java:91)
    	at exc.util.omompx.main(omompx.java:388)

**Comment by hidetoshi-iwashita** [comment]
docs/STATUS-CAF.mdに書いてある制限事項です．
coarrayはstructure componentになれません．
