### ISSUE TITLE
decompile 時に構造型の型情報が見つからずAbend

### ISSUE THREAD

**Issue by a-wada-rk** [omni-compiler/omni-compiler#24]
[環境]
- 任意

[サンプル1]

```
MODULE real_poly_module
  TYPE,PUBLIC :: real_poly
  END TYPE
CONTAINS
  TYPE(real_poly) FUNCTION rp_add_r(poly,real)
    TYPE(real_poly),INTENT(IN) :: poly
    REAL,INTENT(IN) :: real
  END FUNCTION
  TYPE(real_poly) FUNCTION r_add_rp(real,poly)
    TYPE(real_poly),INTENT(IN) :: poly
    REAL,INTENT(IN) :: real
  END FUNCTION
END MODULE

PROGRAM example
  USE real_poly_module
  TYPE(real_poly) p
END
```

[現象1]

```
Exception in thread "main" java.lang.IllegalStateException: not found type name of 'Sf14680'
    at xcodeml.f.decompile.XfTypeManagerForDom.getAliasTypeName(XfTypeManagerForDom.java:345)
    at xcodeml.f.decompile.XfTypeManagerForDom.getAliasTypeName(XfTypeManagerForDom.java:342)
    at xcodeml.f.decompile.XfTypeManagerForDom.getAliasTypeName(XfTypeManagerForDom.java:342)
    at xcodeml.f.decompile.XfDecompileDomVisitor._writeSymbolDecl(XfDecompileDomVisitor.java:464)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$2100(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$VarDeclVisitor.enter(XfDecompileDomVisitor.java:5663)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:649)
    at xcodeml.f.decompile.XfDecompileDomVisitor._invokeChildEnter(XfDecompileDomVisitor.java:626)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$200(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$DeclarationsVisitor.enter(XfDecompileDomVisitor.java:1561)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:649)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$500(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$FfunctionDefinitionVisitor.enter(XfDecompileDomVisitor.java:2895)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:649)
    at xcodeml.f.decompile.XfDecompileDomVisitor._invokeEnter(XfDecompileDomVisitor.java:530)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$1400(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$FcontainsStatementVisitor.enter(XfDecompileDomVisitor.java:2099)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:649)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$500(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$FmoduleDefinitionVisitor.enter(XfDecompileDomVisitor.java:3291)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:649)
    at xcodeml.f.decompile.XfDecompileDomVisitor._invokeChildEnter(XfDecompileDomVisitor.java:626)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$200(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$GlobalDeclarationsVisitor.enter(XfDecompileDomVisitor.java:1352)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:649)
    at xcodeml.f.decompile.XfDecompileDomVisitor._invokeChildEnter(XfDecompileDomVisitor.java:633)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$200(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$XcodeProgramVisitor.enter(XfDecompileDomVisitor.java:1226)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:108)
    at xcodeml.f.util.XmfDecompiler.decompile(XmfDecompiler.java:79)
    at exc.util.omompx.main(omompx.java:551)
```

[サンプル2]

```
program type_example
  implicit none

  type S
    real :: a
    real :: b
    real :: c
  end type S

  interface S
    procedure S_init
  end interface S

  type(S) m

  m = S(a=0.0,b=1.0,c=2.0)
  print *, m

contains
  type(S) function S_init(this, a, b, c)
    type(S) this
    real :: a, b, c
  end function S_init
end program type_example
```

[現象2]

```
Exception in thread "main" java.lang.IllegalStateException: not found type name of 'S164f490'
    at xcodeml.f.decompile.XfTypeManagerForDom.getAliasTypeName(XfTypeManagerForDom.java:345)
    at xcodeml.f.decompile.XfTypeManagerForDom.getAliasTypeName(XfTypeManagerForDom.java:342)
    at xcodeml.f.decompile.XfTypeManagerForDom.getAliasTypeName(XfTypeManagerForDom.java:342)
    at xcodeml.f.decompile.XfDecompileDomVisitor._writeSymbolDecl(XfDecompileDomVisitor.java:464)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$2100(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$VarDeclVisitor.enter(XfDecompileDomVisitor.java:5663)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:649)
    at xcodeml.f.decompile.XfDecompileDomVisitor._invokeChildEnter(XfDecompileDomVisitor.java:626)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$200(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$DeclarationsVisitor.enter(XfDecompileDomVisitor.java:1561)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:649)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$500(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$FfunctionDefinitionVisitor.enter(XfDecompileDomVisitor.java:2895)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:649)
    at xcodeml.f.decompile.XfDecompileDomVisitor._invokeChildEnter(XfDecompileDomVisitor.java:633)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$200(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$GlobalDeclarationsVisitor.enter(XfDecompileDomVisitor.java:1352)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:649)
    at xcodeml.f.decompile.XfDecompileDomVisitor._invokeChildEnter(XfDecompileDomVisitor.java:633)
    at xcodeml.f.decompile.XfDecompileDomVisitor.access$200(XfDecompileDomVisitor.java:37)
    at xcodeml.f.decompile.XfDecompileDomVisitor$XcodeProgramVisitor.enter(XfDecompileDomVisitor.java:1226)
    at xcodeml.f.decompile.XfDecompileDomVisitor._enter(XfDecompileDomVisitor.java:1188)
    at xcodeml.f.decompile.XfDecompileDomVisitor.invokeEnter(XfDecompileDomVisitor.java:108)
    at xcodeml.f.util.XmfDecompiler.decompile(XmfDecompiler.java:79)
    at exc.util.omompx.main(omompx.java:551)
```

**Comment by h-murai** [comment]
サンプル2に対して、F_Frontで以下のようなワーニングが出るが、デコンパイルは通るようになっている。

```
$ F_Front foo.f90
"foo.f90", line 16: warning: can't determine a function to be actually called for a generic interface function call of 's', this is a current limitation.
...
```

**Comment by h-murai** [comment]
いつの間にか直っていた → クローズ
