### ISSUE TITLE
[F]bcast指示文に構造体の要素を指定できない

### ISSUE THREAD

**Issue by mnakao** [omni-compiler/omni-compiler#241]
Version:1.2.0, Git Hash:757864b2でテスト。

bcast指示文に構造体の要素を指定すると、コンパイル時にエラーになる。

```Fortran
program test
  implicit none
  type mytype
     integer:: a
  end type mytype
  type(mytype):: mt
!$xmp nodes p(*)
  mt%a = 2
!$xmp bcast (mt%a)
  print*, mt%a

end program test
```
> % xmpf90 a.f90
> "a.f90", line 9:(XMP) not variable in bcast variable list
> Exception in thread "main" java.lang.UnsupportedOperationException: (MEMBER_REF:int (F_VAR_REF:S868b20 (VAR:S868b20 mt, local)) (IDENT a, null))
> 	at exc.object.XobjList.getName(XobjList.java:405)
> 	at exc.xmpF.XMPanalyzePragma.analyzeBcast(XMPanalyzePragma.java:712)
> 	at exc.xmpF.XMPanalyzePragma.analyzePragma(XMPanalyzePragma.java:215)
> 	at exc.xmpF.XMPanalyzePragma.run(XMPanalyzePragma.java:67)
> 	at exc.xmpF.XMPtranslate.doDef(XMPtranslate.java:292)
> 	at exc.object.XobjectDefEnv.iterateDef(XobjectDefEnv.java:90)
> 	at exc.util.omompx.main(omompx.java:402)

**Comment by h-murai** [comment]
構造体の成分、配列要素、連続な部分配列の参照には対応したが、不連続な部分配列には未対応。また、reductionでも同じ問題はある。備忘のため残す。
