### ISSUE TITLE
再帰的構造体があるときF_Frontの動作異常

### ISSUE THREAD

**Issue by hidetoshi-iwashita** [omni-compiler/omni-compiler#33]
以下のような構造型のcoarrayを宣言すると，F_Frontは空のファイルを出力するため，
後続のシェルスクリプトでcore dumpしています．

sh-4.1$ cat bug3.f90
  program struct_pointer

    type g1
       integer a(3)
       type(g1),pointer :: p
    end type g1

    type(g1), save ::  cs1[*]

  end program
sh-4.1$ xmpf90 --verbose bug3.f90
mkdir -p /tmp/__omni_tmp__12849
/home/iwashita/Project/OMNI-clone/bin/F_Front -fxmp -I/home/iwashita/Project/OMNI-clone/include -M. bug3.f90 -o /tmp/__omni_tmp__12849/bug3_f90_in.xml
/home/iwashita/Project/OMNI-clone/libexec/omni_common_lib.sh: line 41: 12923 Segmentation fault      (core dumped) ${@+"$@"}
rm -rf /tmp/__omni_tmp__12849

構造体宣言で自身を指すポインタがあるときに発生するようです．
別の構造体を指すポインタがあるときには正常動作します．

sh-4.1$ cat bug3OK.f90 
  program get1

    type g0
       integer a(3)
    end type g0

    type g1
       integer a(3)
       type(g0),pointer :: p
    end type g1

    type(g1), save ::  cs1[*]

  end program
sh-4.1$ xmpf90 bug3OK.f90 
sh-4.1$

**Comment by h-murai** [comment]
修正できたと思いますが、トランスレータで以下のようにエラーになるので、ブランチrecursiveStructとしてpushしました。

```
$ xmpf90 -c --tmp foo.f90
Exception in thread "main" java.lang.StackOverflowError
	at exc.object.XobjConst.getFkind(XobjConst.java:26)
	at exc.object.XobjInt.copy(XobjInt.java:33)
	at exc.object.Xobject.cfold(Xobject.java:884)
	at exc.object.FindexRange.getSizeFromLbUb(FindexRange.java:167)
	at exc.object.FindexRange.getExtent(FindexRange.java:113)
	at exc.object.FarrayType.getExtent(FarrayType.java:112)
	at exc.object.FarrayType.getTotalArraySizeExpr(FarrayType.java:68)
	at exc.xmpF.XMPcoarray._getNumElements(XMPcoarray.java:680)
	at exc.xmpF.XMPcoarray._getDerivedTypeLength_atmost(XMPcoarray.java:701)
	at exc.xmpF.XMPcoarray._getElementLength_atmost(XMPcoarray.java:662)
	at exc.xmpF.XMPcoarray._getDerivedTypeLength_atmost(XMPcoarray.java:700)
	at exc.xmpF.XMPcoarray._getElementLength_atmost(XMPcoarray.java:662)
	at exc.xmpF.XMPcoarray._getDerivedTypeLength_atmost(XMPcoarray.java:700)
	at exc.xmpF.XMPcoarray._getElementLength_atmost(XMPcoarray.java:662)
	at exc.xmpF.XMPcoarray._getDerivedTypeLength_atmost(XMPcoarray.java:700)
	at exc.xmpF.XMPcoarray._getElementLength_atmost(XMPcoarray.java:662)
    ...
```

**Comment by hidetoshi-iwashita** [comment]
確認しました．

早速の対応ありがとうございます．
