### ISSUE TITLE
多次元分散配列をxmp_mallocで作成した場合の変換ミス

### ISSUE THREAD

**Issue by mnakao** [omni-compiler/omni-compiler#489]
例えば、下記コードがコンパイルできない。
```C
#include <xmp.h>

int main(){
  int size = 10;
  int (*a)[size];
  a = (int (*)[size])xmp_malloc(xmp_desc_of(a), size, size);
#pragma xmp nodes p[1][1]
#pragma xmp template t[size][size]
#pragma xmp distribute t[block][block] onto p
#pragma xmp align a[i][j] with t[i][j]

  a[0][0] = 0;
  return 0;
}
```
>  % xmpcc a.c 
> a.c: In function ‘xmpc_main’:
> a.c:17:2: error: invalid type argument of unary ‘*’ (have ‘int’)
>  a[0][0] = 0;

**Comment by mnakao** [comment]
下記のコードでも、本チケットと同じ問題が起きる（原因が同根であるかは不明）。

```C
#include <xmp.h>
int (*a)[3];
int main(int argc, char** argv)
{
  int b[3];
    a = (int (*)[3])xmp_malloc(xmp_desc_of(a), 3, 3);
#pragma xmp nodes p[3][1]
#pragma xmp template t[3][3]
#pragma xmp distribute t[block][block] onto p
#pragma xmp align a[i][j] with t[i][j]

    int iii = 2;
#pragma xmp gmove
    b[0:3] = a[0:3][iii];

  return 0;
}
```
なお、gmove中のiiiが定数の場合は、正常終了する。

> % xmpcc a.c
> Exception in thread "main" java.lang.NullPointerException: i=1, args=(INDEX_RANGE (INT_CONSTANT:int 0x0) (INT_CONSTANT:int 0x3) (INT_CONSTANT:int 0x1))
> 	at exc.object.XobjList.getArg(XobjList.java:268)
> 	at exc.xcalablemp.XMPtranslateLocalPragma.buildGmoveDesc(XMPtranslateLocalPragma.java:3006)
> 	at exc.xcalablemp.XMPtranslateLocalPragma.translateGmove(XMPtranslateLocalPragma.java:2932)
> 	at exc.xcalablemp.XMPtranslateLocalPragma.translatePragma(XMPtranslateLocalPragma.java:101)
> 	at exc.xcalablemp.XMPtranslateLocalPragma.translate(XMPtranslateLocalPragma.java:47)
> 	at exc.xcalablemp.XMPtranslate.translate(XMPtranslate.java:65)
> 	at exc.xcalablemp.XMPtranslate.doDef(XMPtranslate.java:36)
> 	at exc.object.XobjectDefEnv.iterateDef(XobjectDefEnv.java:90)
> 	at exc.util.omompx.main(omompx.java:328)

C_Frontが出力するXMLファイル中に変数iiiの情報はあるのに、.XMPtranslateLocalPragma.translateの時点で、その変数の情報が消えている。

**Comment by h-murai** [comment]
xmp_mallocの有無に拠らず、分散されたポインタを一次元配列として扱う場合しか考慮されていないのが原因。

一つ目については`XMPrewriteExpr.rewritePointerRef`を、二つ目については`XMPtranslateLocalPragma.convertArrayToLoop`を、それぞれ修正する必要がある。

なお、ループ内に出現する場合は、`XMPrewriteExpr.rewriteArrayRefInLoop`において対応できている。

**Comment by mnakao** [comment]
2つ目については、array指示文でなく、gmove指示文なので、convertArrayToLoopは関係なさそうです。

**Comment by h-murai** [comment]
2つ目は、683d4c8で修正しました。

**Comment by mnakao** [comment]
ありがとうございます。2つ目について、テストを追加しておきました。

**Comment by atabuchi** [comment]
XACC のコンパイルで OpenACC 側に影響があるか調査しました。
はじめに動的確保する多次元分散配列ですが、
```C
  int size;
  int (*a)[size];
```
のように配列長の一部が変数である2次元以上の配列型は Omni OpenACC は対応してないので、
```C
  #define SIZE 10
  int (*a)[SIZE];
```
として定数にしてチェックをしました。

XACC で Omni OpenACC を使ってコンパイルすると型の不整合でエラーが出ました。
問題箇所は xmp_malloc() で確保する分散配列の Ident の型の変更で、
Ident.setType() で型を変更するだけでは、Ident.Ref() が返す Xobject の型は元のままとなっていました。
そこで、Ident.setValue() (コメントによると value は base address expression value)
も設定するようにしたところ解決しました。
69cbcc1 で修正、 f6fc488 でテストを追加してあります。


次に、XMP や OpenACC というより全体的に member_array_ref でエラーがありました。
以下のコードで xmpcc でエラーがでます。
```C
int main()
{
    struct mytype {
        double v[10];
    };
    struct mytype v2L;

    v2L.v[0] = 1.0;
    return 0;
}
```
> $ xmpcc member_array_ref.c
Exception in thread "main" java.lang.UnsupportedOperationException: (MEMBER_ARRAY_REF:A5 (ADDR_OF:<P:S0> (VAR:S0 v2L, local)) (IDENT v, null))
        at exc.object.Xobject.getSym(Xobject.java:266)
        at exc.xcalablemp.XMPrewriteExpr.rewriteArrayRef(XMPrewriteExpr.java:1616)
        at exc.xcalablemp.XMPrewriteExpr.rewriteExpr(XMPrewriteExpr.java:1332)
        at exc.xcalablemp.XMPrewriteExpr.rewriteAssignExpr(XMPrewriteExpr.java:147)
        at exc.xcalablemp.XMPrewriteExpr.rewriteFuncExprs(XMPrewriteExpr.java:118)
        at exc.xcalablemp.XMPrewriteExpr.rewrite(XMPrewriteExpr.java:31)
        at exc.xcalablemp.XMPtranslate.translate(XMPtranslate.java:68)
        at exc.xcalablemp.XMPtranslate.doDef(XMPtranslate.java:36)
        at exc.object.XobjectDefEnv.iterateDef(XobjectDefEnv.java:90)
        at exc.util.omompx.main(omompx.java:328)

出力された XcodeML の該当箇所
```XML
<arrayRef type="double">
    <memberArrayRef type="A5" member="v">
        <varAddr type="P0" scope="local">v2L</varAddr>
    </memberArrayRef>
    <intConstant type="int">0</intConstant>
</arrayRef>
```
arrayRef の1つ目の要素に memberArrayRef が来ることが想定されていないようです。
XMP rewriter だけでなく C_Backend, OpenACC でも問題があると思います。
