### ISSUE TITLE
stdlib.hをインクルードし、最適化オプションをつけるとエラー

### ISSUE THREAD

**Issue by atabuchi** [omni-compiler/omni-compiler#608]
stdlib.hをインクルードするコードを-O1以上の最適化オプションでコンパイルするとトランスレータでエラーになる。
おそらくgccのバージョンが新しいと起こる。

### 環境
- Ubuntu 18.04.2 LTS
- gcc 7.3.0
- Omni compiler master(437d9f65)

### 再現コード

```C
#include <stdlib.h>

int main(void){
  return 0;
}
```

### 実行結果

```
$ xmpcc test.c
$ xmpcc test.c -O1
Exception in thread "main" java.lang.IllegalArgumentException
	at xcodeml.util.XmStringUtil.getAsCLong(XmStringUtil.java:99)
	at xcodeml.util.XmStringUtil.getAsCInt(XmStringUtil.java:42)
	at exc.xcodeml.XcodeMLtools_C.getAsCInt(XcodeMLtools_C.java:1025)
	at exc.xcodeml.XcodeMLtools_C.toXobject(XcodeMLtools_C.java:236)
	at exc.xcodeml.XcodeMLtools.getChildList(XcodeMLtools.java:203)
	at exc.xcodeml.XcodeMLtools_C.toXobject(XcodeMLtools_C.java:497)
	at exc.xcodeml.XcodeMLtools.getChildList(XcodeMLtools.java:203)
	at exc.xcodeml.XcodeMLtools_C.toXobject(XcodeMLtools_C.java:497)
	at exc.xcodeml.XcodeMLtools.getChildList(XcodeMLtools.java:203)
	at exc.xcodeml.XcodeMLtools_C.toXobject(XcodeMLtools_C.java:497)
	at exc.xcodeml.XcodeMLtools.getChildList(XcodeMLtools.java:203)
	at exc.xcodeml.XcodeMLtools_C.toXobject(XcodeMLtools_C.java:497)
	at exc.xcodeml.XcodeMLtools.getChildList(XcodeMLtools.java:203)
	at exc.xcodeml.XcodeMLtools_C.toXobject(XcodeMLtools_C.java:497)
	at exc.xcodeml.XcodeMLtools.getChildList(XcodeMLtools.java:203)
	at exc.xcodeml.XcodeMLtools_C.toXobject(XcodeMLtools_C.java:497)
	at exc.xcodeml.XcodeMLtools_C.toXobjList(XcodeMLtools_C.java:641)
	at exc.xcodeml.XcodeMLtools_C.enterAsXobjList(XcodeMLtools_C.java:607)
	at exc.xcodeml.XcodeMLtools_C.toXobject(XcodeMLtools_C.java:262)
	at exc.xcodeml.XcodeMLtools_C.toXobjList(XcodeMLtools_C.java:641)
	at exc.xcodeml.XcodeMLtools_C.enterAsXobjList(XcodeMLtools_C.java:636)
	at exc.xcodeml.XcodeMLtools_C.toXobject(XcodeMLtools_C.java:118)
	at exc.xcodeml.XcodeMLtools_C.enterGlobalDecl(XcodeMLtools_C.java:66)
	at exc.xcodeml.XcodeMLtools.read(XcodeMLtools.java:128)
	at exc.util.omompx.main(omompx.java:288)
```

**Comment by h-murai** [comment]
以下で再現する。おそらく、XcodeML-Commnにおける、unsigned long int定数の扱いに問題がある。

```c
unsigned long int x = 0xfffff00000000000u;
```
