### ISSUE TITLE
task region内で外側のloopのindexを使用するとエラー

### ISSUE THREAD

**Issue by ytn86** [omni-compiler/omni-compiler#611]
下記のようなtaskのプログラムをコンパイルするとエラーが発生する．
エラー内容から，translatorにおいてiをpp_iに置き換えるが，pp_iが定義されていないのが原因のように見える．

```
extern hoge(int i);

void test()
{
#pragma omp parallel num_threads(1) num_threads(1)
        {
        #pragma omp single
                {
                        for (int i=0; i<32; i++) {
#pragma omp task
                                i; //will be translated to pp_i
                        }
                }
        }
}
```

```
Exception in thread "main" xcodeml.util.XmTranslationException: <Var> variable 'pp_i' is not defined                                                                                                                                                                                    at xcodeml.c.util.XmcXcodeToXcTranslator._getIdent(XmcXcodeToXcTranslator.java:2641)                                                                                                                                                                                            at xcodeml.c.util.XmcXcodeToXcTranslator$VarVisitor.enter(XmcXcodeToXcTranslator.java:1526)                                                                                                                                                                                     at xcodeml.c.util.XmcXcodeToXcTranslator.trans(XmcXcodeToXcTranslator.java:96)                                                                                                                                                                                                  at xcodeml.c.util.XmcXcodeToXcTranslator.transChildren(XmcXcodeToXcTranslator.java:106)                                                                                                                                                                                         at xcodeml.c.util.XmcXcodeToXcTranslator.access$000(XmcXcodeToXcTranslator.java:55)                                                                                                                                                                                             at xcodeml.c.util.XmcXcodeToXcTranslator$PointerRefVisitor.enter(XmcXcodeToXcTranslator.java:1626)                                                                                                                                                                              at xcodeml.c.util.XmcXcodeToXcTranslator.trans(XmcXcodeToXcTranslator.java:96)                                                                                                                                                                                                  at xcodeml.c.util.XmcXcodeToXcTranslator.transChildren(XmcXcodeToXcTranslator.java:106)                                                                                                                                                                                         at xcodeml.c.util.XmcXcodeToXcTranslator.access$000(XmcXcodeToXcTranslator.java:55)                                                                                                                                                                                             at xcodeml.c.util.XmcXcodeToXcTranslator$ExprStatementNodeVisitor.enter(XmcXcodeToXcTranslator.java:177)                                                                                                                                                                        at xcodeml.c.util.XmcXcodeToXcTranslator.trans(XmcXcodeToXcTranslator.java:96)                                                                                                                                                                                                  at xcodeml.c.util.XmcXcodeToXcTranslator.enterNodes(XmcXcodeToXcTranslator.java:2414)                                                                                                                                                                                           at xcodeml.c.util.XmcXcodeToXcTranslator.enterNodes(XmcXcodeToXcTranslator.java:2403)                                                                                                                                                                                           at xcodeml.c.util.XmcXcodeToXcTranslator$OMPPragmaVisitor.enter(XmcXcodeToXcTranslator.java:1897)        
```

**Comment by ytn86** [comment]
このprefix `pp_` は，OMPinfoでの処理で追加される．

https://github.com/omni-compiler/omni-compiler/blob/master/XcodeML-Exc-Tools/src/exc/openmp/OMPinfo.java
