### ISSUE TITLE
ファイルを跨ぐモジュールのモジュール名が見えない

### ISSUE THREAD

**Issue by hidetoshi-iwashita** [omni-compiler/omni-compiler#85]
佐藤さん
ファイル跨ぎモジュールの件、残念ながらまだ問題があるようです。
坂上さんのプログラムが通りません。

原因を調べました。
以下、現象を再現する縮小プログラムです。

```
klogin4$ cat test2.f90 
  subroutine test2
    use test2m
    real*8 :: abc(lx)[*], def(lx)

    limgn = 1
    abc(:)[limgn+1] = def(:)

    return
  end subroutine test2
klogin4$ cat test2m.f90 
module test2m
  integer, parameter :: lx = 2048
  integer :: limgn, llbz, lubz
end module test2m
klogin4$ 
```
xmpf90に通すと、test2m が見つからないと言って落ちます。

```
klogin4$` xmpf90 -c test2m.f90 --debug
Create __omni_tmp__/
klogin4$ xmpf90 -c test2.f90 --debug
Create __omni_tmp__/
fatal: Ident.cfold: not found module name in globalSymbols: test2m
java.lang.Exception: Stack trace
    at java.lang.Thread.dumpStack(Thread.java:1365)
    at xcodeml.util.XmLog.fatal(XmLog.java:89)
    at exc.object.Ident.cfold(Ident.java:363)
    at exc.object.XobjString.cfold(XobjString.java:88)
    at exc.object.FconstFolder.evalAsInitializationExpr(FconstFolder.java:113)
    at exc.object.FconstFolder.run(FconstFolder.java:55)
    at exc.object.XobjList.cfold(XobjList.java:550)
    at exc.xmpF.XMPcoarray._calcMinusExprExpr(XMPcoarray.java:1501)
    at exc.xmpF.XMPcoarray.getImageIndex_opt(XMPcoarray.java:1327)
    at exc.xmpF.XMPcoarray.getImageIndex(XMPcoarray.java:1299)
    at exc.xmpF.XMPcoindexObj._makeActualArgs_type8(XMPcoindexObj.java:497)
    at exc.xmpF.XMPcoindexObj._makeActualArgs_type8(XMPcoindexObj.java:483)
    at exc.xmpF.XMPcoindexObj.toCallStmt_type8(XMPcoindexObj.java:401)
    at exc.xmpF.XMPcoindexObj.toCallStmt(XMPcoindexObj.java:388)
    at exc.xmpF.XMPtransCoarrayRun.coindexVarStmtToCallStmt(XMPtransCoarrayRun.java:1929)
    at exc.xmpF.XMPtransCoarrayRun.convCoidxStmtsToSubrCalls(XMPtransCoarrayRun.java:1896)
    at exc.xmpF.XMPtransCoarrayRun.transExecPart(XMPtransCoarrayRun.java:1353)
    at exc.xmpF.XMPtransCoarrayRun.run1_procedure(XMPtransCoarrayRun.java:707)
    at exc.xmpF.XMPtransCoarrayRun.run1(XMPtransCoarrayRun.java:677)
    at exc.xmpF.XMPtransCoarray.doDef(XMPtransCoarray.java:103)
    at exc.object.XobjectDefEnv.iterateDef(XobjectDefEnv.java:91)
    at exc.util.omompx.main(omompx.java:400)
klogin4$ 
````

catで１ファイルにしてからxmpf90にかけると通ります。

```
klogin4$ cat test2m.f90 test2.f90 >x.f90
klogin4$ xmpf90 -c x.f90 --debug
Create __omni_tmp__/
klogin4$ 
````

catしない場合とした場合でF_Frontの出力を比べると、catしない場合には 
<globalSymbols> の中にモジュール名 test2m がないことが分かります。

catしない場合
```
 <globalSymbols>
    <id type="Fe99ac0" sclass="ffunc">
      <name>test2</name>
    </id>
  </globalSymbols>
````
catした場合
```
 <globalSymbols>
    <id sclass="ffunc">
      <name>test2m</name>
    </id>
    <id type="F16888d0" sclass="ffunc">
      <name>test2</name>
    </id>
  </globalSymbols>
````

**Comment by mitsuhisa-sato** [comment]
$BN;2r$G$9!#(B

-- M. Sato

2017/01/24 18:33$B!"(BHidetoshi Iwashita <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by hidetoshi-iwashita** [comment]
報告者：岩下

修正確認しました。

テストプログラムは次のpush時に反映されます。
tests/xcalablemp/local-view/coarray/F/SCOPE/
bug085m.f90 と bug085.f90 の組合せ
